# Dependencies
#markdown: redcarpet
markdown: rdiscount
highlighter: pygments

# Permalinks pretty
permalink: pretty

# Setup
title: RUDY

tagline: '随笔'
description: '他看起来好像一条狗耶'
url: http://www.rudywang.com

author:
  name: 'rudy'
  email: servenaring@gmail.com

paginate: 100
subscribe_rss: /pages/atom.xml

# Custom vars
version: 0.0.1

# Comments

#comments :
#    provider : duoshuo
#    duoshuo :
#          short_name : cellier-me


